[package]
name = "clipsway"
version = "0.1.0"
authors = ["Gef11"]
edition = "2018"

[dependencies]
wl-clipboard-rs = "^0.3"
clap = "^2"
lazy_static = "^1"
ron = "^0.6"
serde = "^1"

[profile.release]
lto = true
codegen-units = 1
